### PR TITLE
Support language of Simplified Chinese

### PR DESCRIPTION
**Pull request by huanxiangspace**
There are more and more Chinese users of Keplr. In order to better serve Keplr users and iconLake users, we have translated it into Simplified Chinese language.
If you have any questions, please feel free to leave any comments.

### CODE REVIEW

**Comment by claraexmachina** [comment]
可以吗，我们将"连接点设置失败"修改为"端点设置失败"？我们不是中文母语者，请告诉我们这是否是一个好主意！

**Comment by huanxiangspace** [comment]
> 可以吗，我们将"连接点设置失败"修改为"端点设置失败"？我们不是中文母语者，请告诉我们这是否是一个好主意！

@claraexmachina Thank for your advise. 

"连接点" makes it easier for Chinese users to understand that this is the access point to the blockchain network. "端点" generally refers to the two ends of the line segment.

Hope this is helpful for understanding.

If you still have doubts, please feel free to leave any comments.

**Comment by claraexmachina** [comment]
ahh okay.  I'm not Chinese, so I'll trust it all in your capable hands. Thank you so much for your invaluable contribution, means a lot to us. 🥰"

**Comment by huanxiangspace** [comment]
> ahh okay. I'm not Chinese, so I'll trust it all in your capable hands. Thank you so much for your invaluable contribution, means a lot to us. 🥰

It's a great honor to contribute code to Keplr. I'm so happy.

**Pull request merged**
