### PR TITLE
Add Echelon

### PR DESCRIPTION
**Pull request by echelonfoundation**
Adding Echelon (ECH) to Keplr

Fork of Evmos, with 100 validators maximum active and full EVM support.

Added ETH derivation conversion of Echelon addresses

https://scout.ech.network

https://ping.ech.network

If you need APIs contact us in Discord: https://discord.gg/ArXNfK99ae

### CODE REVIEW

**Comment by echelonfoundation** [comment]
@Thunnini Why was this closed? Are we missing something to be added? I have tested it locally with config.vars set and works great!

**Comment by echelonfoundation** [comment]
@Thunnini Should I reopen this PR?

**Comment by Thunnini** [comment]
You shouldn't reopen this PR. Feel free to use the permissionless 'suggestChain' feature.

**Comment by echelonfoundation** [comment]
> You shouldn't reopen this PR. Feel free to use the permissionless 'suggestChain' feature.



> You shouldn't reopen this PR. Feel free to use the permissionless 'suggestChain' feature.

We wish to be added into Keplr Wallet natively. Having to suggest the chain is a great permissionless temporary work around, which we will employ, but to be officially added as an option to Keplr would be our main mission and goal. We will more than likely re-open a PR, so you do not even have to do any code to add us, the next PR we will ensure is cleaner without upstream merges.

**Comment by echelonfoundation** [comment]
> You shouldn't reopen this PR. Feel free to use the permissionless 'suggestChain' feature.



> You shouldn't reopen this PR. Feel free to use the permissionless 'suggestChain' feature.

We wish to be added into Keplr Wallet natively. Having to suggest the chain is a great permissionless temporary work around, which we will employ, but to be officially added as an option to Keplr would be our main mission and goal. We will more than likely re-open a PR, so you do not even have to do any code to add us, the next PR we will ensure is cleaner without upstream merges.

**Pull request closed without merging**
