### PR TITLE
Update cosmwasm REST query path

### PR DESCRIPTION
**Pull request by giansalex**
Update cosmwasm query path, reference [v0.24 CHANGELOG](https://github.com/CosmWasm/wasmd/blob/v0.24.0/CHANGELOG.md#v0240-2022-03-09)

Juno will updated to wasm v0.24 in the next software-upgrade.

### CODE REVIEW

**Comment by giansalex** [comment]
This pull_request should be ready after
[Proposal N° 17](https://www.mintscan.io/juno/proposals/17)

**Comment by Thunnini** [comment]
Is this PR ready for review? We also need to think about backward compatibility since cosmwasm is not only being used by Juno

**Comment by Thunnini** [comment]
A "wasmd_0.24+" feature has been added. If the wasm version is higher than 0.24, the feature should be added automatically. Is there currently a live Juno testnet? Or do you think you can help test this by using Keplr v0.10.0, without the "wasmd_0.24+" feature in the config then checking if "wasmd_0.24+" feature automatically gets added and verifying the queries work well.

@giansalex

**Comment by giansalex** [comment]
I see it uses the new url, balances and transfer are also ok.
image

**Pull request merged**
