### PR TITLE
chore: allow injective to use ledger

### PR DESCRIPTION
**Pull request by bangjelkoski**
Hello 👋🏻  We've seen that (thanks to the Evmos team) Ledger support is now available on Keplr for Etheremint-compatible accounts. After trying out the implementation we've seen that there are restrictions as to which chain can use this feature. 

As a permissionless and open-source project restrictions on usage seem a bit harsh and extreme measure to take. So, we've pushed a fix to allow the Injective community to use this implementation as well.

### CODE REVIEW

**Comment by Thunnini** [comment]
However, even if it is slightly different from ethermint, we plan to modify it so that it can be used with ledger. Maybe by the end of the year or early next year, it will be implemented so that it can be used in chains such as injective, so please wait.

**Comment by bangjelkoski** [comment]
> First of all, you should not use "or" operator, but use "and" operator for your purpose. 🤷‍♂️ Before request PR to open source project, at least, you should build, run and check that it can work. And, I wrote down the reason why I approve the ledger interaction with only Evmos. There is a comment above the 7th line of the one line you edited, so why didn't you read it? I wrote the code based on ethermint and injective uses modified code from ethermint, so it is not compatible. I've marked the user that keplr don't support it because it doesn't actually work.

Thanks for the review. I've updated the PR with the proper conditional. I forgot to update my local fork with the codebase I used for testing as I wanted to get support for Ledger for our users as soon as possible. 

The only difference we have is the `typeUrl`, everything else is the same. Injective launched before Evmos so it’s not necessarily that we knew only the Ethermint type would be supported and that one is the one everyone should use. Knowing this, is there any way we could speed up the support for Injective?

**Comment by Thunnini** [comment]
I thought that all chains that support ethermint specify the ethereum chain id in the chain id like evmos_9000-1. Later I found out that injective is not that format of chain id. The biggest problem at present is that the method of obtaining the ethereum chain id from injective is too different from evmos.
(So what is the ethereum chain id in injective?)

**Comment by bangjelkoski** [comment]
> I thought that all chains that support ethermint must specify the ethereum chain id in the chain id like evmos_9000-1. Later I found out that injective is not that format of chain id. The biggest problem at present is that the method of obtaining the ethereum chain id from injective is too different from evmos. (So what is the ethereum chain id in injective?)

In the beginning, we wanted to use Ethermint and the EVM environment it provides to execute our exchange logic. At that point in time, it wasn't the right choice for us and we decided to build our own blockchain using the CosmosSDK and have the logic encapsulated using native go modules. We kept the Ethereum compatibility that Ethermint offered out of the box because it felt like the right thing to do (from both the onboarding perspective and having wallet support) but we changed the `typeUrl` because we didn't want developers to get confused that we are built on top of Ethermint.

**Comment by Thunnini** [comment]
Basically, in case of kava or evmos, it has the chain id such as evmos_9000-1. In this case, the chain id of ethereum evm is 9000. However, since injective doesn't have this type of chain id, ethereum chain id cannot be known.
I'll advise on a solution for short term.
 - Modify the `EthermintChainIdHelper.parse()` of @keplr-wallet/cosmos to return the hardcoded ethereum chain id in case of injective.
 - Modify eip712 to be processed on injective in Cosmos account store
and fix the rest of the problems...

**Comment by bangjelkoski** [comment]
Hey :wave:, @Thunnini @austinchandra can you guys look at the implementation I did? There were some differences in how Evmos and Injective handle the EIP712 so I refactored the codebase to look cleaner by using functions that will generate the proper values needed. 

I've tested both Injective and Evmos using Ledger on the Ledger extension to sign a `MsgSend` transaction and they were working fine. I just wanted to hear your guys' thoughts and I'll continue testing and fixing issues if I find any in the meantime.

**Comment by austinchandra** [comment]
Personally, I think this should be split into two separate PRs: one that purely restructures code, and a second that provides support for Injective. This would simplify review and isolate each PR to one change at a time.

**Comment by bangjelkoski** [comment]
> Personally, I think this should be split into two separate PRs: one that purely restructures code, and a second that provides support for Injective. This would simplify review and isolate each PR to one change at a time.

In restructuring the code you mean the function calls I did in the `broadcastMsgs` function in the cosmos store?

**Comment by austinchandra** [comment]
> > Personally, I think this should be split into two separate PRs: one that purely restructures code, and a second that provides support for Injective. This would simplify review and isolate each PR to one change at a time.
> 
> In restructuring the code you mean the function calls I did in the `broadcastMsgs` function in the cosmos store?

Everything that is not specific to Injective.

**Comment by Thunnini** [comment]
Agree with @austinchandra. But it's okay to go this way. But there is no need to add other libraries to dependencies. These are functions that can be done with the existing library. And adding "ethereumjs-util" to use `bufferToHex` is completely useless. Use `Buffer.from(value).toString("hex")`. And when using Buffer, use `import { Buffer } from "buffer/";`. "Buffer" only exists in nodejs. Webpack automatically inserts the polyfill, but since this code is actually used only in the web browser, it is better to import it explicitly.

**Comment by bangjelkoski** [comment]
> Agree with @austinchandra. But it's okay to go this way. But there is no need to add other libraries to dependencies. These are functions that can be done with the existing library. And adding "ethereumjs-util" to use `bufferToHex` is completely useless. Use `Buffer.from(value).toString("hex")`. And when using Buffer, use `import { Buffer } from "buffer/";`. "Buffer" only exists in nodejs. Webpack automatically inserts the polyfill, but since this code is actually used only in the web browser, it is better to import it explicitly.

Resolved and pushed.

**Comment by Thunnini** [comment]
- Please revert output has in @keplr-wallet/proto-types
- Please use existing library instead of Eth-sig-utils

**Comment by bangjelkoski** [comment]
Resolved @Thunnini

**Comment by Thunnini** [comment]
This PR does enable ledger support but seems to create an signature error for mnemonic and private keys. Please double check if all logic are correct.

**Comment by bangjelkoski** [comment]
> This PR does enable ledger support but seems to create an signature error for mnemonic and private keys. Please double check if all logic are correct.

On it, thank you for reviewing it. I'll get back to you asap.

**Comment by Thunnini** [comment]
I made changes before your last commit, so I manually applied your commit and merged. Perhaps this is why this PR is not automatically closed. Anyway, this PR has been merged.

**Pull request closed without merging**
