### PR TITLE
Remove signer checks from verifyADR36AminoSignDoc

### PR DESCRIPTION
**Pull request by findolor**
When trying to verify an arbitrary data using the verifyArbitrary method, if the signer address is not the same with current address that is stored in key, we get an error.

This PR fixes this issue by:

- Removing the signer check with the address in key, allowing for any given address to be used in verification.
- Changing the pub_key variable to be used from the account response (account info of the given signer) in the pub_key check.

### CODE REVIEW

**Comment by Thunnini** [comment]
The original intention was to verify ADR36 only for the selected account. If you need a more generalized solution for verifying ADR36, use `verifyADR36AminoSignDoc` function in the @keplr-wallet/cosmos package or use own way to verify

**Comment by findolor** [comment]
So if I'm trying to verify someone else's message with their signature and address, I can't do it now. I thought it makes sense to get the data from the other person and verify the message on my end.

Basically I must write custom verification code in this case right?

**Comment by findolor** [comment]
@Thunnini ```verifyADR36Amino``` did the job for me. Thanks for pointing that out!

**Comment by Thunnini** [comment]
That’s great! Closing this issue!

**Pull request closed without merging**
