### PR TITLE
Update Umee avg gas price

### PR DESCRIPTION
**Pull request by robert-zaremba**
bumping umee avg gas price. We are adjusting the gas price and will be rolling it out on mainnet.

BTW, when will be the next Keplr release (when the adjusted values will be effective in keplr wallet)?

### CODE REVIEW

**Comment by Thunnini** [comment]
Make a PR to https://github.com/chainapsis/keplr-chain-registry

**Comment by HeesungB** [comment]
@robert-zaremba  Can I close this issue?

https://github.com/chainapsis/keplr-chain-registry/pull/77 this PR is merged!

**Comment by robert-zaremba** [comment]
Yes, if this is not needed, then we can close it. 
Could you explain how the [packages/extension/src/config.ts](https://github.com/chainapsis/keplr-wallet/pull/644/files#diff-7568c12e6b54856861f4ebeddb283e34303327290cf95eba47ed5e121255d447) is used? Is it deprecated?

**Comment by HeesungB** [comment]
@robert-zaremba 
I think we did this for convenience.
First, most people don't know enough about config files to modify them.

Also, changes to the config file had to be redeployed for it to take effect, so it was slow to reflect changes to the chain information.

But now the information is readily available to everyone and changes can be quickly applied to extension, mobile, and dashboard.

**Comment by robert-zaremba** [comment]
Thanks for response @HeesungB . How often the updates from keplr-chain-registry are deployed to the browser extension? In other words, once the PR is merged in keplr-chain-registry, when it will be visible in the production?

**Comment by HeesungB** [comment]
@robert-zaremba  Apply to your extension immediately!

Updates the extension chain information by fetching the value in the chain registry when the extension is turned on.

**Comment by robert-zaremba** [comment]
> Updates the extension chain information by fetching the value in the chain registry when the extension is turned on.

So, is a Keplr user going to have updated gas price right after the PR is merged?

**Comment by HeesungB** [comment]
@robert-zaremba Yes!

**Comment by robert-zaremba** [comment]
Ok, thank you. Let's close the PR.

**Pull request closed without merging**
