### PR TITLE
Update config.ts, Add $PSTAKE.

### PR DESCRIPTION
**Pull request by puneet2019**

### CODE REVIEW

**Comment by Thunnini** [comment]
The ibc token is automatically displayed when the user has it, so why should it be set as the default?

**Comment by puneet2019** [comment]
So this token is generated from gravity, would like to see it as $PSTAKE, rather than gravityXXX
Gravity chain is not natively supported right now, so I thought it would be better.

**Comment by puneet2019** [comment]
image
It looks like this for 0.9 $PSTAKE.

and the sendcoins button too looks not so great

image

**Comment by puneet2019** [comment]
i think this is not required, so closing this

**Pull request closed without merging**
