### PR TITLE
Add qrcode process

### PR DESCRIPTION
**Pull request by renfengshi**

### CODE REVIEW

**Comment by HeesungB** [comment]
@renfengshi Hello.
Could you move the `/extension/src/components/progress/index.tsx` to `/extension/src/pages/register/components`?
I don't think this component will be used globally.

**Comment by renfengshi** [comment]
> @renfengshi Hello. Could you move the `/extension/src/components/progress/index.tsx` to `/extension/src/pages/register/components`? I don't think this component will be used globally.

@HeesungB 
It's also used by `packages/extension/src/pages/sign/components/keystone/scan.tsx` in signing page, not just connecting page. Looking at it this way, is it more appropriate to put global?

**Comment by HeesungB** [comment]
@renfengshi 
Since there aren't many places where it's used, could you just code that part yourself and leave it out of the component?

I know the team promised to only include components that are universally used, but progerss is only used in `Keystone`.

**Comment by renfengshi** [comment]
@HeesungB OK, I will move it to an another place.

**Comment by renfengshi** [comment]
@HeesungB It's moved to keystone.

**Pull request merged**
