### PR TITLE
Add stkATOM to currencies

### PR DESCRIPTION
**Pull request by saurabhfegade**

### CODE REVIEW

**Comment by Thunnini** [comment]
Can you explain why this PR is needed?

Also please use linter when submitting a PR.

**Comment by puneet2019** [comment]
> Can you explain why this PR is needed?

hey @Thunnini , would be great to see stk/uatom in the keplr drop down, 
persistence is going to start minting stk/uatom with it's coming upgrade.
the coin-denom is decided to be stk/uatom.

The reason for early PR is so that we do not have to scrabble for this during/ post launch

**Comment by Thunnini** [comment]
When’s this update?

**Comment by puneet2019** [comment]
we are planning for October end chain upgrade

**Comment by Thunnini** [comment]
ACK, could you ping me one week before the upgrade when the final date for the upgrade has been decided?

**Comment by puneet2019** [comment]
awesome! will let you know once the upgrade proposal is on chain, we have 7day voting period, so that should do.

**Comment by puneet2019** [comment]
hey @Thunnini 
the upgrade proposal is out - 
https://www.mintscan.io/persistence/proposals/8

**Pull request merged**
