### PR TITLE
Added support for searching cw20 contracts

### PR DESCRIPTION
**Pull request by kromsten**
#### Added ContractStore that work in similar manner as ChainSuggestStore. The data is fetched from a [Community Repository](https://github.com/kromsten/contract-registry) following the same model as [Chain Registry Repository](https://github.com/chainapsis/keplr-chain-registry). The community repository is encouraged to be forked / contributed to.

New modal follows the same standard as AddressBookModal

Screenshot 2023-06-15 at 15 12 36
Screenshot 2023-06-15 at 15 12 54
Screenshot 2023-06-15 at 15 13 35
Screenshot 2023-06-15 at 15 14 02

### CODE REVIEW

**Comment by Thunnini** [comment]
Thanks for your input, we sincerely appreciate your efforts! However we would like to ask for further information before we actually merge this PR:
- We would like to know if there is any additional intent or motive behind this PR, like participating to a bounty program or running a private business. If there's any, please let us know.
- It seems like the repo is not a community repo, but your individual repo (Let us know if it is not correct!). Would it be okay for you if we fork it and manage it on our own?
- Do you have any plans to operate it for cw20 contract addresses on other chains as well, along with secret network?

Please understand that this is a necessary step for us to keep the quality and the control of our product at its highest standard. Thank you again for your contribution!

**Comment by kromsten** [comment]
Totally valid questions. I was hoping you'd ask some of them.

- Yes. There is a Secret Network bounty for adding support for this exact feature. However I made an extra effort for making the code changes generalisable for any cosmwasm network, which wasn't explicitly incentivised.
- That specific repository is an example of what a community repository can be. Having someone with more resources to maintain it would be the perfect scenario and I can only encourage that. Having it under my account is a backup option in case there is no party interested in doing so. Apologies for sending the wrong message.
- I indeed had some plans of adding popular contracts across CosmWasm ecosystem. However the idea was not to be limited by cw20 only and have other type of contracts such as cw721 curated as well. The changes proposed in the PR can tell them apart by checking the type of a contract.

**Comment by kromsten** [comment]
Migration to another repository should be really straightforward by changing appropriate values inside `CommunityContractsInfoRepo` in `packages/extension/src/config.ts`

**Comment by HeesungB** [comment]
@kromsten 
There are a few things to fix, so I've been working on them at [this link](https://github.com/chainapsis/keplr-wallet/pull/787) #787! They should be live soon!

**Pull request merged**
